name: Build and deploy .NET Core application to Function App OneIntegPaymentSync
on:
  push:
    branches:
    - feature/daily-payment-sync
permissions:
  id-token: write
  contents: read
env:
  AZURE_FUNCTIONAPP_NAME: OneIntegPaymentSync
  AZURE_FUNCTIONAPP_PACKAGE_PATH: OneInteg.Function/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: OneInteg.Function
  DOTNET_CORE_VERSION_INPROC: 6.0.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Setup .NET Core (for inproc extensions)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION_INPROC }}
        dotnet-quality: preview
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Archive publish output
      run: |
        cd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        zip -r ../functions.zip .
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/functions.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/functions.zip
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.OneIntegPaymentSync_CLIENT_ID_DF4C }}
        tenant-id: ${{ vars.OneIntegPaymentSync_TENANT_ID_DF4C }}
        subscription-id: ${{ vars.OneIntegPaymentSync_SUBSCRIPTION_ID_DF4C }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/functions.zip
